[package]
name="edgedb_rust_listdatabases"
version="0.0.1"
edition = "2021"

[dependencies]
edgedb-client = "0.3.0"
async-std = {version="1.10", features=[
    "unstable", # Condvar
]}
env_logger = "0.9.0"


[workspace]
